# Generated by Django 5.2.8 on 2025-12-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard_app', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_age', models.BooleanField(default=True)),
                ('show_department', models.BooleanField(default=True)),
                ('show_photo', models.BooleanField(default=True)),
            ],
        ),
    ]
