# Generated by Django 5.2.8 on 2025-12-31 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard_app', '0006_savedtemplate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedtemplate',
            old_name='data',
            new_name='json',
        ),
        migrations.RemoveField(
            model_name='savedtemplate',
            name='side',
        ),
        migrations.AddField(
            model_name='savedtemplate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='savedtemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savedtemplate',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
