# Generated by Django 5.2.8 on 2026-01-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard_app', '0007_rename_data_savedtemplate_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsettings',
            name='show_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='show_blood_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='show_date_of_birth',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='show_emergency_mobile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='show_phone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='show_role',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='show_roll_no',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='show_signature',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dashboardsettings',
            name='show_valid_upto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='valid_upto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
