# Generated by Django 5.2.8 on 2026-01-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard_app', '0008_dashboardsettings_show_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardsettings',
            name='show_residence_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='residence_status',
            field=models.CharField(blank=True, choices=[('resident', 'Resident'), ('non-resident', 'Non-Resident'), ('temporary', 'Temporary'), ('international', 'International')], default='resident', max_length=20, null=True),
        ),
    ]
