# Generated by Django 5.2.8 on 2026-01-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcard_app', '0009_dashboardsettings_show_residence_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='residence_status',
            field=models.CharField(blank=True, choices=[('hostel', 'Hostel'), ('dayscholar', 'Day Scholar')], max_length=20, null=True),
        ),
    ]
